### ISSUE TITLE
调用异常

### ISSUE THREAD

**Issue by Sunshine9794** [growingio/ReactNativeDemo#1]
安装依赖包后报错
Error: GrowingIO RN SDK 代码调用异常: TypeError: null is not an object (evaluating '_$$_REQUIRE(_dependencyMap[14], "react-native").NativeModules.GrowingIOModule.prepareView')

This error is located at:
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)

<unknown>
    ReactNativeRenderer-dev.js:4015:38
createInstance
    ReactNativeRenderer-dev.js:4016:3
completeWork
    ReactNativeRenderer-dev.js:14449:12
completeUnitOfWork
    ReactNativeRenderer-dev.js:17106:10
performUnitOfWork
    ReactNativeRenderer-dev.js:17316:30
workLoop
    ReactNativeRenderer-dev.js:17328:41
renderRoot
    ReactNativeRenderer-dev.js:17429:15
performWorkOnRoot
    ReactNativeRenderer-dev.js:18435:17
performWork
    ReactNativeRenderer-dev.js:18336:24
performSyncWork
    ReactNativeRenderer-dev.js:18297:14
requestWork
    ReactNativeRenderer-dev.js:18181:19
scheduleWork
    ReactNativeRenderer-dev.js:17981:16
scheduleRootUpdate
    ReactNativeRenderer-dev.js:18654:15
render
    ReactNativeRenderer-dev.js:19524:20
renderApplication
    renderApplication.js:61:34
run
    AppRegistry.js:104:10
runApplication
    AppRegistry.js:198:26
__callFunction
    MessageQueue.js:366:47
<unknown>
    MessageQueue.js:106:26
__guard
    MessageQueue.js:314:10
callFunctionReturnFlushedQueue
    MessageQueue.js:105:17
callFunctionReturnFlushedQueue
    [native code]:0

**Comment by NanNanCHN** [comment]
@Sunshine9794 您好
1.如果是安卓的问题可以参考https://github.com/growingio/react-native-growingio/issues/7
2.如果是iOS的问题,请留意这一步 
![image](https://user-images.githubusercontent.com/8380241/62816847-cf8e2f80-bb5f-11e9-8d03-720d26f335a9.png)

**Comment by NanNanCHN** [comment]
无回复先关闭
