### ISSUE TITLE
依赖找不到

### ISSUE THREAD

**Issue by heiheiwanne** [growingio/ReactNativeDemo#2]
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.growingio.android.test:t-vds-gradle-plugin:RN-autotrack-2.7.7.

**Comment by lizwangying** [comment]
@heiheiwanne  不好意思， 版本号使用了测试版本， 我马上换成正式版本

**Comment by lizwangying** [comment]
已经更新，抱歉哈。
