### ISSUE TITLE
增加RN 0.60.5版本支持和react-navigation 4.0.5版本支持

### ISSUE THREAD

**Issue by GoingAI** [growingio/ReactNativeDemo#3]
增加RN 最新版本支持和react-navigation 最新版本支持

**Comment by musicode** [comment]
+1

**Comment by lizwangying** [comment]
@imliujun @musicode   收到反馈，我们会尽快排期兼容高版本，因为RN发版很频繁，GIO对于RN平台的无埋点兼容希望等待RN 6.x稳定版本，希望理解。
